title: portfolYOU
description: >-
  I turn coffee :coffee: into code,
  use tabs over spaces,
  and never break production.
baseurl: ""             # Empty because user site (username.github.io)
remote_theme: yousinix/portfolYOU
plugins:
  - jemoji

author:
  name: Nirbhay Borikar
  image: https://i.imgur.com/uyDNQnn.jpg
  email: nirbhayborikar@gmail.com
  github: nirbhayborikar
  linkedin: nirbhayborikar
  facebook: nirbhayborikar
  behance: nirbhayborikar

collections:
  projects:
    output: true
    permalink: /projects/:name

permalink: /blog/:title

exclude:
  - README.md
  - LICENSE
  - CONTRIBUTING.md
  - "*.log"

